# Window
enable_audio_bell no
placement_strategy center
window_padding_width 5

# Font
font_size 15.0
font_family      FreeMono Regular
text_composition_strategy legacy

# Keybindings
map ctrl+backspace send_text all \x17
map ctrl+f         send_text all cls && fastfetch\r
map ctrl+shift+enter new_tab
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab
map ctrl+shift+w close_tab

# Visuals
background_image ~/.config/kitty/wallpaper.png
background_image_layout cscaled
background #000000
foreground #ffffff

