window_padding_width 5

font_size 15.0
font_family      FreeMono Regular
text_composition_strategy legacy

background #000000
foreground #ffffff

map ctrl+backspace send_text all \x17
map ctrl+f         send_text all cls && fastfetch\r

background_image ~/.config/kitty/wallpaper.png
background_image_layout scaled
